name: Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'joao208'
      - run: git config --global user.email 'augustoj311@gmail.com'
      - run: npm ci
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'joao208'
      - run: git config --global user.email 'augustoj311@gmail.com'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
